site_name: iceoryx.io
site_url: https://iceoryx.io
repo_url: https://github.com/eclipse/iceoryx
docs_dir: doc/website/
remote_branch: main
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - toc:
      permalink: 🔗
  - meta
  - markdown_include.include:
      base_path: doc
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - awesome-pages
  - search
theme:
  name: 'material'
  font: false
  logo: https://user-images.githubusercontent.com/8661268/114322343-016b4c80-9b20-11eb-853b-bff3739da457.png
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css