# This workflow builds & runs test cases in iceoryx

name: Build & Test

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds & runs iceoryx tests in ubuntu-18.04
  ubuntu-iceoryx:
     # The type of runner that the job will run on
     runs-on: ubuntu-18.04

     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - name: Install iceoryx dependencies
         # Softwares installed in ubuntu-18.04 instance
         # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
         run: sudo apt-get update && sudo apt-get install -y libacl1-dev libncurses5-dev

       - name : Checkout
         uses: actions/checkout@v2

       - name: Build sources
         run: |
            export NUM_CORES=`nproc`
            $GITHUB_WORKSPACE/tools/iceoryx_build_test.sh strict buildall out-of-tree -j $NUM_CORES

       - name: Run timeless tests
         run: |
           cd $GITHUB_WORKSPACE/build
           make all_tests

       - name: Run timing tests
         run: |
           cd $GITHUB_WORKSPACE/build
           make timing_tests

 # This job builds & runs iceoryx tests in macos-10.15
  macos-build-script:
    runs-on: macos-10.15
    # Softwares installed in macos-10.15 instance
    # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: Build ncurses from source
      # tinfo library which is required by iceoryx_introspection isn't available in mac
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p build
          cd build
          git clone https://github.com/mirror/ncurses.git
          cd ncurses
          git checkout v6.2
          ./configure  --prefix=$GITHUB_WORKSPACE/build/install/prefix/ --exec-prefix=$GITHUB_WORKSPACE/build/install/prefix/ --with-termlib
          make
          make install

      - name: Build sources
        run: |
          export NUM_CORES=`sysctl -n hw.ncpu`
          $GITHUB_WORKSPACE/tools/iceoryx_build_test.sh strict build-test binding-c out-of-tree introspection -j $NUM_CORES

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/build
          make all_tests

 # This job builds & runs iceoryx tests in Windows 2019
  windows-iceoryx-meta:
    runs-on: windows-latest
    # Softwares installed in windows instance
    # https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: Build sources
        run: |
          cmake -Bbuild -Hiceoryx_meta -DBUILD_TEST=ON -DINTROSPECTION=OFF -DBINDING_C=ON -DEXAMPLES=ON && cmake --build build
