name: Code Linting on Pull-Requests

on:
  pull_request:
    branches: [ master, release* ]

jobs:
  clang-tidy-review:
    runs-on: ubuntu-20.04

    steps:
      - name: compiler versions
        run: |
          echo $(gcc --version)
          echo $(clang --version)

      - name: Install iceoryx dependencies and clang-tidy
        # Softwares installed in ubuntu-20.04 instance
        # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md
        run: sudo apt-get update && sudo apt-get install -y libacl1-dev libncurses5-dev clang-tidy-12

      # - name: scan
        #uses: actions/checkout@v2
        #uses: jitterbit/get-changed-files@v1
        #run: ./tools/scripts/clang_tidy_check.sh ci_pull_request ${{ steps.scan.outputs.added_modified }}
        # Using the latest master commit to make use of 'cmake_command' and 'config_file' options

