# This workflow only runs manually to build an iceoryx release and publish it into an existing Github Release

name: iceoryx release

on:
  workflow_dispatch:
    inputs:
      patch:
      ReleaseBranch:
        description: 'ReleaseBranch or Tag release_[major].[minor]'
        required: true

jobs:
  build-ubuntu18-04-release:
    runs-on: ubuntu-18.04
    steps:
      - name: check if committer starts workflow, otherwise cancel the job
        uses: andymckay/cancel-action@0.2
        if: |
          ${{ github.actor != 'budrus' || github.actor != 'dkroenke' || github.actor != 'mossmaurice'
          || github.actor != 'elfenpfiff' || github.actor != 'elboberido' || github.actor != 'marthtz'
          || github.actor != 'ariexi' || github.actor != 'ithier' || github.actor != 'MatthiasKillat' }}

      - name: Install iceoryx dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libacl1-dev libncurses5-dev doxygen graphviz texlive-font-utils
          sudo apt-get install -y plantuml texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-fonts-recommended

      - name: Checkout
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            ref: ${{ github.event.inputs.ReleaseBranch }}

      - name: Build sources
        run: |
          $GITHUB_WORKSPACE/tools/iceoryx_build_test.sh build-strict build-all out-of-tree

      - name: Run timeless tests
        run: |
          cd $GITHUB_WORKSPACE/build
          make all_tests

      - name: Run timing tests
        run: |
          cd $GITHUB_WORKSPACE/build
          make timing_tests

      - name: Build debian package
        run: |
          $GITHUB_WORKSPACE/tools/iceoryx_build_test.sh clean dds-gateway package

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu_18_04_debian
          path: ./build_package/iceoryx*.deb

# This job must be put at the end to collect all release assets from the previous jobs
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: Ubuntu_18_04_debian

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          draft: true
          prerelease: true
          files: |
            ./iceoryx*.deb
