name: Check with clang-tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, release* ]

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04

    steps:
      - name: compiler versions
        run: |
          echo $(gcc --version)
          echo $(clang --version)

      - name: Install iceoryx dependencies and clang-tidy
        # Softwares installed in ubuntu-20.04 instance
        # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md
        run: sudo apt-get update && sudo apt-get install -y libacl1-dev libncurses5-dev clang-tidy-10

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          CC:   clang-10
          CXX:  clang++-10
        run: |
          $GITHUB_WORKSPACE/tools/iceoryx_build_test.sh

      - name: Run clang-tidy
        run: ./tools/check_clang_tidy.sh
